### ISSUE TITLE
Centralpoint

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center-kms#134] opened 2019-03-11 11:18 UTC
Basic viability

- [ ]  is cloud-ready
- [ ]  is FEDRAMPed
- [ ]  is actively supported (with a release in the past year)
- [ ]  has active developer community
- [ ]  has customer support

**Comment by brandocalrissian** [comment] 2019-03-11 15:05
Duplicate of #132

**Closed as completed by brandocalrissian** 2019-03-11 15:05 UTC
